config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show] do
    resources :products
    resources :services
  end

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category_product_parent, :class_name => 'CategoryProduct', optional: true
  has_many :category_product_children, :class_name => 'CategoryProduct', :foreign_key => 'category_product_id', dependent: :destroy
  has_many :products, dependent: :destroy
end

app/models/category_service.rb
class CategoryService < ApplicationRecord
  belongs_to :category_service_parent, :class_name => 'CategoryService', optional: true
  has_many :category_service_children, :class_name => 'CategoryService', :foreign_key => 'category_service_id', dependent: :destroy
  has_many :services, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :comment_parent, :class_name => 'Comment', optional: true
  has_many :comment_children, :class_name => 'Comment', :foreign_key => 'comment_id', dependent: :destroy
  has_many :comment_items, dependent: :destroy
  accepts_nested_attributes_for :comment_items 
end

app/models/comment_item.rb
class CommentItem < ApplicationRecord
  belongs_to :comment
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_items, dependent: :destroy
  has_many :post_categories, dependent: :destroy
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post_item.rb
class PostItem < ApplicationRecord
  belongs_to :post
  belongs_to :product, optional: true
  belongs_to :service, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category_product
  belongs_to :user
  has_many :product_pictures, dependent: :destroy
  has_many :post_items, dependent: :destroy
end

app/models/product_picture.rb
class ProductPicture < ApplicationRecord
  belongs_to :product, dependent: :destroy
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category_service
  belongs_to :user
  has_many :service_pictures, dependent: :destroy
  has_many :post_items, dependent: :destroy
end

app/models/service_picture.rb
class ServicePicture < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord

  has_many :services, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  private

    def comment_params
      params.require(:comment).permit(:content, comment_item_attributes: [:product_id, :service_id, :name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all.order("RANDOM()").limit(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def show
    @comments = @post.comments
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :description, :location, :user_id)
    end
end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base

  private

    def service_params
      params.require(:service).permit(:name, :description, :location, :category_service_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :service_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :service_description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :service_location %>
  </div>

  <div class="field">
    <%= form.label :category_service_id %>
    <%= form.text_field :category_service_id, id: :service_category_service_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :service_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Category service</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.location %></td>
        <td><%= service.category_service %></td>
        <td><%= service.user %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @service.location %>
</p>

<p>
  <strong>Category service:</strong>
  <%= @service.category_service %>
</p>

<p>
  <strong>User:</strong>
  <%= @service.user %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>