config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show] do
    resources :products
    resources :services
  end

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category_product_parent, :class_name => 'CategoryProduct', optional: true
  has_many :category_product_children, :class_name => 'CategoryProduct', :foreign_key => 'category_product_id', dependent: :destroy
  has_many :products, dependent: :destroy
end

app/models/category_service.rb
class CategoryService < ApplicationRecord
  belongs_to :category_service_parent, :class_name => 'CategoryService', optional: true
  has_many :category_service_children, :class_name => 'CategoryService', :foreign_key => 'category_service_id', dependent: :destroy
  has_many :services, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :comment_parent, :class_name => 'Comment', optional: true
  has_many :comment_children, :class_name => 'Comment', :foreign_key => 'comment_id', dependent: :destroy
  has_many :comment_items, dependent: :destroy
  accepts_nested_attributes_for :comment_items 
end

app/models/comment_item.rb
class CommentItem < ApplicationRecord
  belongs_to :comment
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_items, dependent: :destroy
  has_many :post_categories, dependent: :destroy
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post_item.rb
class PostItem < ApplicationRecord
  belongs_to :post
  belongs_to :product, optional: true
  belongs_to :service, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category_product
  belongs_to :user
  has_many :product_pictures, dependent: :destroy
  has_many :post_items, dependent: :destroy
end

app/models/product_picture.rb
class ProductPicture < ApplicationRecord
  belongs_to :product, dependent: :destroy
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category_service
  belongs_to :user
  has_many :service_pictures, dependent: :destroy
  has_many :post_items, dependent: :destroy
end

app/models/service_picture.rb
class ServicePicture < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord

  has_many :services, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  private

    def comment_params
      params.require(:comment).permit(:content, comment_item_attributes: [:product_id, :service_id, :name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all.order("RANDOM()").limit(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def show
    @comments = @post.comments
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :description, :location, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  private

    def product_params
      params.require(:product).permit(:name, :description, :state, :quantity, :location, :category_product_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :post_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :post_location %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :post_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.description %></td>
        <td><%= post.location %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong><%= @post.name %></strong>
</h3>

<div class="row" style="color: black;">
  <div class="col-md-12">
    <div class="card bg-light mb-3">
      <div class="card-header">
        Tengo:
      </div>
      <div class="body">
        <% @post.post_items.where(wants: false).each do |item| %>
          <% if item.product != nil %>
            <div class="row">
              <div class="col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <%= image_tag item.product.product_pictures.order(:number).first.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.product.product_pictures.order(:number).second.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.product.product_pictures.order(:number).third.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.product.product_pictures.order(:number).fourth.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.product.product_pictures.order(:number).fifth.picture, class: "d-block w-100" %>
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Siguiente</span>
                  </a>
                </div>
              </div>
              <div class="col-md-6">
                <h3><%= item.name %></h3>
                <p><%= item.product.description %></p>
                <span class="badge badge-info"><%= item.product.state %></span>
                <span class="badge badge-info">Cantidad: <%= item.product.quantity %></span>
              </div>
            </div>
            <br>
          <% elsif item.service != nil %>
            <div class="row">
              <div class="col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <%= image_tag item.service.service_pictures.order(:number).first.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.service.service_pictures.order(:number).second.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.service.service_pictures.order(:number).third.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.service.service_pictures.order(:number).fourth.picture, class: "d-block w-100" %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag item.service.service_pictures.order(:number).fifth.picture, class: "d-block w-100" %>
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Siguiente</span>
                  </a>
                </div>
              </div>
              <div class="col-md-6">
                <h3><%= item.name %></h3>
                <p><%= item.service.description %></p>
              </div>
            </div>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row" style="color: black;">
  <div class="col-md-12">
    <div class="card bg-light mb-3">
      <div class="card-header">
        Quiero:
      </div>
      <div class="body text-center">
        <br>
        <div class="row align-items-center h-100">
          <% i = 0 %>
          <% @post.post_items.where(wants: true).each do |item| %>
            <% i = i + 1 %>
            <% if i > 1 %>
              <span class="badge badge-primary">+</span>
            <% end %>
            <div class="col-sm-3">
              <div class="card border-primary mb-3" style="max-width: 15rem;">
                <div class="card-header">
                  <%= item.name %>
                </div>
              </div>
            </div>
          <% end %>
          <% @post.post_categories.where(wants: true).each do |category| %>
            <% i = i + 1 %>
            <% if i > 1 %>
              <span class="badge badge-primary">+</span>
            <% end %>
            <div class="col-md-3">
              <div class="card border-primary mb-3" style="max-width: 15rem;">
                <div class="card-header">
                  <% if category.category_product != nil %>
                    <%= category.category_product.name %>
                  <% elsif category.category_service != nil %>
                    <%= category.category_service.name %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<p>
  <%= @post.description %>
</p>

<p>
  <strong>Ubicación:</strong>
  <%= @post.location %>
</p>

<p>
  <strong>Creado por:</strong>
  <%= link_to @post.user.name, user_path(@post.user) %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>
<hr>

<% if user_signed_in? %>
  <h3>Ingresar un nuevo comentario:</h3>

  <%= form_with model: [@post, Comment.new] do |f| %>
    <div class="form-group">
      <%= f.label :comentario %>
      <%= f.text_field :content, class: "form-control", placeholder: "Ingrese su comentario" %>
    </div>
    <div class="form-group">
      <%= f.label "Tengo:" %><br>
      <%= fields_for :comment_items do |cif| %>
        <%= cif.collection_select(:product_id, current_user.products, :id, :name, :include_blank => "Nada seleccionado")%>
      <% end %>
    </div>
    <%= f.submit "Enviar comentario", class: "btn btn-primary" %>
  <% end %>
  <hr>
<% end %>
<h3>Comentarios:</h3>

<% @comments.each do |comment| %>
  <div class="row align-items-center h-100" id="comment<%= comment.id %>">
    <div class="col-md-12">
      <div class="card text-white bg-primary mb-3">
        <div class="card-header"><%= link_to comment.user.name, user_path(comment.user), style: "color: white;" %></div>
        <div class="card-body">
          <p><%= comment.content %></p>
          <br>
          <% i = 0 %>
          <div class="row" style="color: black;">
            <% comment.comment_items.where(wants: false).each do |item| %>
              <% i = i + 1 %>
              <% if i > 1 %>
                <span class="badge badge-primary">+</span>
              <% end %>
              <div class="col-sm-3 card-text">
                <div class="card border-primary mb-3" style="max-width: 15rem;">
                  <div class="card-header">
                    <%= item.name %>
                  </div>
                  <div class="body text-center">
                    <%= image_tag item.picture, width: '90%', style: "display: inline-block;" %>
                  </div>
                </div>
              </div>
            <% end %>
            <span class="badge badge-primary">por</span>
            <% i = 0 %>
            <% comment.comment_items.where(wants: true).each do |item| %>
              <% i = i + 1 %>
              <% if i > 1 %>
                <span class="badge badge-primary">+</span>
              <% end %>
              <div class="col-sm-3">
                <div class="card border-primary mb-3" style="max-width: 15rem;">
                  <div class="card-header">
                    <%= item.name %>
                  </div>
                  <div class="body text-center">
                    <%= image_tag item.picture, width: '90%', style: "display: inline-block;" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :product_state %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :product_location %>
  </div>

  <div class="field">
    <%= form.label :category_product_id %>
    <%= form.text_field :category_product_id, id: :product_category_product_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :product_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>State</th>
      <th>Quantity</th>
      <th>Location</th>
      <th>Category product</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.state %></td>
        <td><%= product.quantity %></td>
        <td><%= product.location %></td>
        <td><%= product.category_product %></td>
        <td><%= product.user %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>State:</strong>
  <%= @product.state %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Location:</strong>
  <%= @product.location %>
</p>

<p>
  <strong>Category product:</strong>
  <%= @product.category_product %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>